baseURL: /acme
languageCode: es-es
title: SHC SERVICIOS WEB
theme: Eclectic

author: 
  facebook: "https://facebook.com/SHCservices" 
  twitter: "https://twitter.com/SHCservices" 
  email: "contact@shcservices.es" 
  name: "SHC SERVICIOS WEB" 
  location: Zaragoza
  phone: (999) 999-9999 
  hours: "**Lunes-Viernes** 8:00AM - 3:00PM" 

menu:
  main: 
    - identifier: curriculum
      name: ACERCA DE
      url: /curriculum
      weight: 40
    - identifier: contacto
      name: CONTACTO
      url: /contacto
      weight: 50 
    - identifier: viajes
      name: VIAJES 
      url: /viajes 
      weight: 100
    - identifier: blog
      name: BLOG 
      url: /blog 
      weight: 60
    - identifier: canales
      name: CANALES 
      url: /television/canales 
      weight: 70
params: 
  colorPickerEnabled: true
  color: "#4546e5"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true